# Generated by Django 3.1.2 on 2020-11-12 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201112_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cap',
            field=models.CharField(default='NC', max_length=5, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='NC', max_length=50, verbose_name='Citt√†'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(default='NC', max_length=10, verbose_name='Numero civico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(default='NC', max_length=30, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(default='NC', max_length=35, verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='NC', max_length=10, validators=[django.core.validators.RegexValidator(message='Numero di telefono errato!', regex='^\\+?1?\\d{10,10}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='via',
            field=models.CharField(default='NC', max_length=50, verbose_name='Via'),
        ),
    ]
